spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  application:
    name:
      PRODUCT-SERVICE
  #  datasource:
  #    url: jdbc:postgresql://localhost:5432/product_listing_service_db
  #    username: postgres
  #    password: rohan15121
  datasource:
    url: jdbc:postgresql://us-east-1.484d70c2-e6c6-4f28-9da7-41fa288fec6c.aws.yugabyte.cloud:5433/yugabyte?ssl=true&sslmode=verify-full&sslrootcert=D:\\aayushi\\RentMitra\\Backrnd-RentMitra-Java\\root.crt
    username: aayushi
    password: "Aayushi@123"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.BooleanDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8081
eureka:
  client:
    service-url.defaultZone:
      http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true
logging:
  level:
    org.springframework.security: DEBUG

